set_custom_cook:
  fields:
    entity_id:
      description: "Number Entity that serves Custom Cook Steps."
      example: "'number.abcdefghi123_cook_cycle'"
      name: Entity
      required: true
      selector:
        entity:
          integration: traeger
          domain: number
    steps:
      required: true
      #Checkout https://github.com/njobrien1006/hass_traeger/blob/master/config/.storage/lovelace#L126 for more examples.
      default:
        - #1 Set temp and smoke, advance on probe fired, or act_temp_adv
          set_temp: 180             #Set grill temp
          smoke: 1                  #S.Smoke if applicable
          act_temp_adv: 170         #Move to next step at this act temp
        - #2 PRE-HEAT....Set timer and use timer to advance. #Probe fire would also advance it.
          time_set: 900             #Set timer
          use_timer: 15             #If set we use the timer to progress if set to zero it won't progress on timer.
        - #3 Set Probe Setpoint and Referance timer. Advance on probe_act_temp_adv (since it is lower than probe setpoint Step #2).
          # `min_delta` AND `max_grill_delta_temp` can be used to increase grill temp within the step.
          probe_set_temp: 205       #Probe Temp
          time_set: 1080            #Set timer in SECONDS but no `use_timer` so this is ref. only.
          min_delta: 30             #Min Delta that the Grill temp will stay at in relation to probe.
          max_grill_delta_temp: 225 #Required for min_delta
          probe_act_temp_adv: 160   #adv the step on probe act temp
        - #4 Advance on probe_act_temp_adv (since it is lower than probe setpoint Step#2).
          # `min_delta` AND `max_grill_delta_temp` can be used to increase grill temp within the step.
          min_delta: 40             #Min Delta that the Grill temp will stay at in relation to probe.
          max_grill_delta_temp: 250 #Required for min_delta
          probe_act_temp_adv: 170   #adv the step on probe act temp
        - #5 Advance on `probe_set_temp` (since it is lower than probe_act_temp_adv).
          # `min_delta` AND `max_grill_delta_temp` can be used to increase grill temp within the step.
          min_delta: 50             #Min Delta that the Grill temp will stay at in relation to probe.
          max_grill_delta_temp: 275 #Required for min_delta
          probe_act_temp_adv: 206   #Adv if probe registered over setpoint in step 2...safety.
        - #6 Set temp to where the probe is @. Set timer. Advance on timer complete
          set_temp: 205             #Go down to probe temp
          time_set: 15              #Wait 15 minutes for somebody to tell me otherwise
          use_timer: 1              #Adv on timer
        - #7 Set for keep warm. Set timer. Advance on timer complete
          keepwarm: 1               #Go down to probe temp
          time_set: 15              #Wait 15 minutes for somebody to tell me otherwise
          use_timer: 1              #Adv on timer
        - #8 Shutdown the grill if the timer is not cancelled.
          shutdown: 1               #Nobody aborted...shutdown.
      selector:
        object:
    set_temp:
      required: false
      example: 180
    smoke:
      required: false
      example: 1
    keepwarm:
      required: false
      example: 0
    time_set:
      required: false
      example: 60
    use_timer:
      required: false
      example: 1
    min_delta:
      required: false
      example: 30
    max_grill_delta_temp:
      required: false
      example: 250
    act_temp_adv:
      required: false
      example: 400
    probe_act_temp_adv:
      required: false
      example: 180
    shutdown:
      required: false
      example: 1